remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
title: Psychic-Tribble
description: Simplify your time with AI-powered scheduling.
baseurl: ""              # or "/psychic-tribble" if you’re using project pages
url: "https://wifiknight45.github.io/psychic-tribble/"
theme: minima            # or your custom layouts in _layouts
markdown: kramdown



